[DEFAULT]
pristine-tar=True
debian-branch = gnupg/stable

[import-orig]
filter = [
 'lang/qt/src/Protocol',
 'lang/qt/src/QGpgMENewCryptoConfig',
 'VERSION',
 '*~',
 '*/*~',
 '*/*/*~',
 '*/*/*/*~',
 '*/*/*/*/*~',
 ]
filter-pristine-tar = False
